const STATUS_CODE_POST = 201;
const ERROR_BAD_REQUEST = 400;
const ERROR_UNAUTHORIZED = 401;
const ERROR_NOT_FOUND = 404;
const ERROR_REQUEST_CONFLICT = 409;
const ERROR_ON_SERVER = 500;

module.exports = {
  STATUS_CODE_POST,
  ERROR_BAD_REQUEST,
  ERROR_UNAUTHORIZED,
  ERROR_NOT_FOUND,
  ERROR_REQUEST_CONFLICT,
  ERROR_ON_SERVER,
};
